services:

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file:
      - ".env"
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    volumes:
      - wp:/var/www/wordpress
      - adminer:/var/www/adminer
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - adminer
    restart: always
    env_file:
      - ".env"

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    env_file:
      - ".env"

  adminer:
    build: ./requirements/adminer
    image: adminer
    container_name: adminer
    volumes:
      - adminer:/var/www/adminer
    networks:
      - inception
    restart: always

  ftp:
    build: ./requirements/ftp
    image: ftp
    container_name: ftp
    volumes:
      - wp:/srv/ftp
    networks:
      - inception
    ports:
      - "20:20"
      - "21:21"
    restart: always

  redis:
    build: ./requirements/redis
    image: redis
    container_name: redis
    networks:
      - inception
    restart: always

  resume:
    build: ./requirements/resume
    image: resume
    container_name: resume
    networks:
      - inception
    restart: always

  mailhog:
    build: ./requirements/mailhog
    image: mailhog
    container_name: mailhog
    networks:
      - inception
    restart: always
    ports:
      - "8025:8025"

networks:
  inception:
    name: inception

secrets:
  pwd:
    file: ../secrets/pwd.txt

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/jeada-si/data/db
      o : bind
      type : none
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/jeada-si/data/wp
      o : bind
      type : none
  adminer:
    name: adminer
    driver: local
    driver_opts:
      device: /home/jeada-si/data/adminer
      o : bind
      type : none
