services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    env_file: ".env"
    environment:
      DB_PWD_FILE: /run/secrets/db_pwd
    secrets:
      - db_pwd
  nginx:
    build: ./requirements/nginx
    image: nginx
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file: ".env"
    ports:
      - "443:443"
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wp:/var/www/wordpress
    networks:
      - inception
    env_file: ".env"

networks:
  inception:
    name: inception

secrets:
  db_pwd:
    file: ../secrets/db_pwd.txt

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      device: /home/jeada-si/data/db
      o : bind
      type : none
  wp:
    name: wp
    driver: local
    driver_opts:
      device: /home/jeada-si/data/wp
      o : bind
      type : none