FROM	debian
RUN		apt-get upgrade && apt-get update
RUN 	apt-get install -y zabbix-agent
RUN 	apt-get install -y zabbix-server-mysql
RUN		apt-get install -y gettext-base
COPY	./zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf
COPY	./zabbix_server.conf /usr/local/etc/zabbix_server.conf
COPY	./init_zabbix.sh /home/init_zabbix.sh
RUN		chmod 777 /home/init_zabbix.sh
ENTRYPOINT [ "/home/init_zabbix.sh" ]