FROM			debian:bullseye
RUN				apt-get update -y
RUN				apt-get upgrade -y
RUN				apt-get install -y php curl php-fpm
RUN				apt-get install -y php-mysql
RUN				apt-get install -y mariadb-client
RUN				apt-get install -y wget
COPY			./init_wp.sh /home/init_wp.sh
RUN				chmod 777 /home/init_wp.sh
COPY			./www.conf /etc/php/7.4/fpm/pool.d/www.conf
ENTRYPOINT		[ "/home/init_wp.sh" ]