FROM	debian:bullseye
RUN		apt-get update -y
RUN		apt-get upgrade -y
RUN		apt-get install nginx -y
RUN		apt-get install -y openssl
RUN		openssl req -x509 -nodes \
	-out /home/wordpress.crt \
	-keyout /home/wordpress.key \
	-subj "/C=FR/ST=Paris/L=Paris/O=42/OU=42/CN=jeada-si.42.fr/UID=admin_name"
RUN		openssl req -x509 -nodes \
	-out /home/adminer.crt \
	-keyout /home/adminer.key \
	-subj "/C=FR/ST=Paris/L=Paris/O=42/OU=42/CN=adminer.42.fr/UID=admin_name"
RUN		openssl req -x509 -nodes \
	-out /home/resume.crt \
	-keyout /home/resume.key \
	-subj "/C=FR/ST=Paris/L=Paris/O=42/OU=42/CN=resume.42.fr/UID=admin_name"
COPY	./nginx.conf /etc/nginx/nginx.conf
CMD		["nginx", "-g", "daemon off;"]